// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthToken struct {
	Key    string    `json:"key"`
	Expire time.Time `json:"expire"`
}

type AuthTokenInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthTokenResponse struct {
	AuthenticationToken *AuthToken `json:"authentication_token"`
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type Mutation struct {
}

type NewUserInput struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}
